spring:
  security:
    oauth2:
      client:
        registration:
          default:
            provider: hmpps-auth
            client-id: approved-premises-api
            client-secret: clientsecret
            authorization-grant-type: client_credentials
        provider:
          hmpps-auth:
            token-uri: ${hmpps-auth.url}/oauth/token
  threads:
    virtual:
      enabled: true

redisson:
  timeout: 3000
  scan:
    interval: 2000
  retry:
    interval: 1500
    attempts: 3
  connection:
    pool-size: 10
    minimum-idle-size: 5

redis:
  replica:
    host:
  host:
  port: 6379
  auth:
    token: