spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sas_db
    username: sas_user
    password: sas_psw

service:
  probation-integration-delius:
    base-url: https://approved-premises-and-delius-dev.hmpps.service.justice.gov.uk
  probation-integration-oasys:
    base-url: https://approved-premises-and-oasys-dev.hmpps.service.justice.gov.uk
  approved-premises-api:
    base-url: https://approved-premises-api-dev.hmpps.service.justice.gov.uk
  core-person-record:
    base-url: https://hmpps-person-record-dev.hmpps.service.justice.gov.uk
  tier:
    base-url: https://hmpps-tier-dev.hmpps.service.justice.gov.uk
  prisoner-search:
    base-url: https://prisoner-search-dev.prison.service.justice.gov.uk
  accommodation-data-domain:
    base-url: https://accommodation-data-domain-api-dev.hmpps.service.justice.gov.uk
  nomis-user-roles:
    base-url: https://nomis-user-roles-api-dev.prison.service.justice.gov.uk

redis:
  host: localhost