hmpps-auth:
  url: https://sign-in-dev.hmpps.service.justice.gov.uk/auth

event:
  details-url:
    proposed-accommodation-updated: http://localhost:8080/proposed-accommodations/#id
    duty-to-refer-created: http://localhost:8080/duty-to-refers/#id

hmpps.sqs:
  useWebToken: false
  provider: localstack
  topics:
    hmpps-domain-event-topic:
      arn: arn:aws:sns:eu-west-2:000000000000:hmpps-domain-event-topic
  queues:
    sas-domain-events-queue:
      queueName: sas_domain_events_queue
      dlqName: sas_domain_events_dlq
      subscribeTopicId: hmpps-domain-event-topic
      subscribeFilter: '{"eventType":["tier.calculation.complete"]}'