hmpps-auth:
  url: https://sign-in-dev.hmpps.service.justice.gov.uk/auth

services:
  ap-delius-context-api:
    base-url: https://approved-premises-and-delius-dev.hmpps.service.justice.gov.uk
  approved-premises-api:
    # base-url: https://approved-premises-api-dev.hmpps.service.justice.gov.uk
    base-url: http://localhost:8080