hmpps-auth:
  url: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"

service:
  probation-integration-delius:
    base-url: https://approved-premises-and-delius-dev.hmpps.service.justice.gov.uk
  probation-integration-oasys:
    base-url: https://approved-premises-and-oasys-dev.hmpps.service.justice.gov.uk
  approved-premises-api:
    base-url: https://approved-premises-api-dev.hmpps.service.justice.gov.uk
  core-person-record:
    base-url: https://hmpps-person-record-dev.hmpps.service.justice.gov.uk

