hmpps-auth:
  url: https://sign-in-dev.hmpps.service.justice.gov.uk/auth

event:
  details-url:
    proposed-accommodation-created: http://localhost:8080/proposed-accommodation/#id

hmpps.sqs:
  useWebToken: false
  provider: localstack
  topics:
    hmpps-domain-event-topic:
      arn: arn:aws:sns:eu-west-2:000000000000:hmpps-domain-event-topic