generic-service:
  nameOverride: hmpps-single-accommodation-service-api
  productId: "HMPPS554" # productId for the product that this belongs too, i.e. DPS001, see README.md for details

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/hmpps-single-accommodation-service-api
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-single-accommodation-service-api-cert

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-single-accommodation-service-api:
#      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DEFAULT_CLIENT-ID: "SYSTEM_CLIENT_SINGLE_ACCOMMODATION_SERVICE_ID"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DEFAULT_CLIENT-SECRET: "SYSTEM_CLIENT_SINGLE_ACCOMMODATION_SERVICE_SECRET"
      SENTRY_DSN: "SENTRY_DSN"

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-single-accommodation-service-api
