---
# Per environment values which override defaults in hmpps-single-accommodation-service-api/values.yaml

generic-service:
  serviceAccountName: hmpps-community-accommodation-api-service-account
  replicaCount: 2

  ingress:
    host: single-accommodation-service-api-dev.hmpps.service.justice.gov.uk
    tlsSecretName: hmpps-single-accommodation-service-api-dev-cert

  env:
    JAVA_OPTS: "-Xmx1000m"
    SPRING_PROFILES_ACTIVE: dev
    HMPPS_AUTH_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    SERVICES_APPROVED-PREMISES-API_BASE-URL: https://approved-premises-api-dev.hmpps.service.justice.gov.uk

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-approved-premises

  env_details:
      production_env: false
