---
# Per environment values which override defaults in hmpps-single-accommodation-service-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: single-accommodation-service-api-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    HMPPS_AUTH_URL: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
    SERVICES_APPROVED-PREMISES-API_BASE-URL: https://approved-premises-api-preprod.hmpps.service.justice.gov.uk

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-approved-premises
